### ISSUE TITLE
Remove NCC?

### ISSUE THREAD

**Issue by MicahZoltu** [Pandapip1/jekyll-label-action#1]
I believe what is here is following some common tutorial because I see this all the time, but is `ncc` actually necessary as a build step?  It makes the output code very hard to read, which means it makes it very hard to audit.  If you were to just do `tsc` and nothing more would things work?  The output code in that case would be far more readable than the webpacked version.

**Comment by Pandapip1** [comment]
`ncc` is required so that we can avoid adding `node_modules` to source control. The main workflow file is `src/action.ts` and is very auditable.

**Comment by MicahZoltu** [comment]
It is auditable if the build is reproducible (see my PR for enabling that).

**Comment by Pandapip1** [comment]
The PR was merged, so the build should be reproducible.

**Comment by MicahZoltu** [comment]
I was able to verify the build output.  Would still be cool to get rid of the bundler but I can appreciate the problem you have described and am OK with punting on this for now.
